apiVersion: v1
kind: Pod
metadata:
  name: cabc-train-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 100
    fsGroup: 100
  containers:
  - name: cabc-processing
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
    env:
    - name: REPO_PATH
      value: /opt/repo/CABC
    command:
    - "bash"
    - "-c"
    args:
    - |
      # --- User and Environment Setup ---
      echo "Running as user: $(whoami), UID: $(id -u), GID: $(id -g)"
      # --- Git Repository Setup ---
      echo "Setting up Git repository..."
      mkdir -p /opt/repo
      cd /opt/repo
      git clone --single-branch -b main https://github.com/Deb-bie/CABC.git CABC
      # --- Install dependencies ---
      echo "Installing required dependencies..."
      cd ${REPO_PATH}
      # pip install dominate visdom wandb
      # --- Install CycleGAN requirements ---
      # echo "Installing CycleGAN requirements..."
      # pip install -r ${REPO_PATH}/pytorch-CycleGAN-and-pix2pix/requirements.txt
      pip install tensorflow_addons
      sleep infinity

    volumeMounts:
    - name: git-repo
      mountPath: /opt/repo
    - name: cabc-data-volume
      mountPath: /data
    resources:
      limits:
        memory: 30Gi
        cpu: "16"
        nvidia.com/gpu: "1"
      requests:
        memory: 24Gi
        cpu: "12"
        nvidia.com/gpu: "1"
  volumes:
  - name: git-repo
    emptyDir: {}
  - name: cabc-data-volume
    persistentVolumeClaim:
      claimName: cabc-data
  restartPolicy: Never