apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cabc-data
spec:
  storageClassName: rook-ceph-block-central
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi